### ISSUE TITLE
Common session pattern and optimization...

### ISSUE THREAD

**Issue by AndreasKl** [AndreasKl/tomatenmark#12]
@thovid I chew about the optimization we merged today and remembered a pattern I used for sessions. 

To force an update for an object stored in the session, I obtained the object from the session map, modified the instance and re-added the instance back to the session.

With the reference check, the modification would now be lost and not written into the store.

**Comment by thovid** [comment]
Yes, you're right. Oh those mutable objects...

**Comment by AndreasKl** [comment]
Solved by #13
